### ISSUE TITLE
Improve Input mode Behavior/Messages

### ISSUE THREAD

**Issue by alexgrejuc** [The-Code-In-Sheep-s-Clothing/bogl-editor#25] opened 2020-04-10 23:40 UTC
(EDIT by @montymxb ) Adding that this issue has been partly resolved with regards to input reprompting until a valid expression has been formed. In addition, `input(board)` is no longer valid in the current syntax, but there is still a need to report the type expected vs. the actual type provided. Putting this here so it can be seen first, as this issue has a long string of comments.

-----

The prompt tells me that it switched back to input mode, but this does not appear to be the case. The next time I call input it just grabs whatever is on the input buffer. Either we should not print this and require them type clear (bad interface) or actually switch. 

I think the clear command is not good because then we have the situation of an undefined/nonvalue. For example if I enter `let x = input(initialBoard) in x + 1` and then clear, how do we evaluate x + 1? 

Anyways, here is the output of the REPL not actually leaving input mode despite what the message says. 

```
> let x = input(initialBoard) in x + 1

Empty	Empty	Empty	Empty	Empty	Empty
Empty	Empty	Empty	Empty	Empty	Empty
Empty	Empty	Empty	Empty	Empty	Empty
Empty	Empty	Empty	Empty	Empty	Empty
Empty	Empty	Empty	Empty	Empty	Empty
Empty	Empty	Empty	Empty	Empty	Empty
Empty	Empty	Empty	Empty	Empty	Empty

Switched to input mode. Type "clear" to go back to normal mode.

> 3

4
Switched back to normal mode.

> let x = input(initialBoard) in x + 1

4
```

**Comment by calgagi** [comment] 2020-05-12 05:17
Couldn't reproduce. Using TikTakToe file, I get:
![image](https://user-images.githubusercontent.com/10853283/81641171-3d100a80-93d5-11ea-910c-9fcd4d4587f1.png)

**Comment by alexgrejuc** [comment] 2020-05-18 03:10
The specific expression depends on how that game file is defined. In the case of TicTacToe.hs, input = Position (which is (Int,Int)). You can change it to input = Int or form a well-typed expression with x : Position. Also, the input function has been changed to not require a board so it would be something like let x = input in ...

**Comment by alexgrejuc** [comment] 2020-05-18 03:30
Source code from the image: 

```
game BuggyInput

type Board = Array (3,3) of Int
type Input = Int
```

`let x = input in x + 1`

**Comment by alexgrejuc** [comment] 2020-05-18 04:08
I think this would be a good interaction for input mode with well-typed input: 
``` 
> input
You are in input mode. Enter an expression of type <type of Input>
> <ill-typed expression>
You entered an expression of type <type>. Enter an expression of type <type of Input>
> <well-typed expression>
<value of the expression>
```

Here is a concrete example where Input = Int
```
input
You are in input mode. Enter an expression of type Int
>sdfsdf
You entered an expression of type Error. Enter an expression of type Int
> True
You entered an expression of type Error. Enter an expression of type Int
```

This might require some backend/API changes, a dirty fix would be to not report the type of the user expression and to glean the expected type of input by reading that line from their source code. 

We can also run into situations where users enter non-terminating expressions. Is there a way to exit input mode in that case? Can we set a timeout? 

I understand that that is probably a lot to do; the minimal fix for input would be to actually exit input mode after the user enters an expression. This should also gracefully handle situations with multiple input such as `let first = input in let second = input in first + second`.

**Comment by montymxb** [comment] 2020-07-10 02:36
Normal input termination mimics clear, and works for cases like `let x = input in let y = input in x + y`, but leaving this open as noted in #49 so that we can keep ideas open for improving the behavior and related responses for using this.

**Comment by montymxb** [comment] 2020-11-09 07:58
Closing this as the input issue has been reworked, should be fine now. If issues with input come up after this latest update we should open up a separate issue. It's changed enough now that a lot of the old context is no longer relevant to how this works.

**Closed by montymxb** 2020-11-09 07:58 UTC
Labels: bug
